services: []

cronJobs:
  - name: tw-stockbot-905
    schedule: "5 1 * * 1-5"   # 週一~週五 01:05 UTC = 台北 09:05
    command: "python -u tw_stockbot_push.py"
    envVars:
      - key: LINE_ACCESS_TOKEN
        sync: false      # 在 Render 控制台設定，不寫進 repo
